version: '3.7'

services:

  web:
    build: .
    image: web
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    command: gunicorn -b 0.0.0.0:8000 nlp_assignment.predict.falcon_app:app
