version: '3.7'

services:

  web:
    build: .
    image: web
    environment:
      - PORT=8080
    container_name: web
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    command: gunicorn -b 0.0.0.0:8080 nlp_assignment.predict.falcon_app:app
